### ISSUE TITLE
Roadmap for `v1.0.0`

### ISSUE THREAD

**Issue by ConorMacBride** [matplotlib/pytest-mpl#198]
I reviewed all the configuration options which are used in the code and found quite a few inconsistencies. I have listed proposed fixes for them, separated into breaking and non-breaking changes. We can add warning for the breaking changes now, and then change in `v1.0.0`.

Let's discuss these lists. Are there any items which should be added or removed? For the breaking changes, how long of a warning period should we have? For any of them, should we only start warning in `v1.0.0` and then change in `v1.1.0`? 

## Review of configuration options

| Option | kwarg | CLI | ini | *default* |
| ------ | ----- | --- | --- | ------- |
||||||
| Enable testing | N/A | `--mpl` | N/A | `False` |
| Enable baseline image generation, at specified directory path (relative to where pytest was run) | N/A | `--mpl-generate-path` | N/A | `None` |
| Enable baseline hash generation, at specified file path (relative to where pytest was run) | N/A | `--mpl-generate-hash-library` | N/A | `None` |
||||||
| Directory containing baseline images <br> (relative to the test file) | `baseline_dir` | `--mpl-baseline-path` <br> **(relative to where pytest was run)** |  | `baseline/` |
| Whether `--mpl-baseline-path` should also be relative to the test file | N/A | `--mpl-baseline-relative` | N/A | `False` |
||||||
| Filename of the baseline image | `filename` | N/A | N/A | test name |
| Whether to include the module name in the baseline image filename <br> **UNDOCUMENTED** | ? |  | `mpl-use-full-test-name` | `False` |
||||||
| File containing baseline hashes <br> (relative to the test file) | `hash_library` | `--mpl-hash-library` |  | no hash comparison |
||||||
| RMS tolerance | `tolerance` |  |  | `2` |
| Whether to standardise metadata | `deterministic` |  |  | `True` (PNG: `False`) |
| kwargs to pass to savefig | `savefig_kwargs` | N/A | N/A | `{}` |
| Matplotlib style | `style` |  |  | `classic` |
| Whether to remove axis tick labels | `remove_text` |  |  | `False` |
| Matplotlib backend <br> **UNDOCUMENTED** | `backend` |  |  | `agg` |
||||||
| Directory to write testing artifacts to <br> (relative to where pytest was run) | N/A | `--mpl-results-path` | `mpl-results-path` | temp dir |
| Whether to save result images for passing tests | N/A | `--mpl-results-always` | `mpl-results-always` | `False` (`True` if generating a HTML summary) |
| Which test summaries to generate, if any | N/A | `--mpl-generate-summary={html,json,basic-html}` |  | `None` |

### Notes
1. N/A are options which we don't think should exist.
1. Empty boxes are options which we do think should exist.
1. ? are options which could exist but would be of limited use.
1. Due to how paths are computed by Python, the baseline directory and hash library paths can be absolute. In this case `--mpl-baseline-relative` and what directory the paths are interpreted to be relative to does not have any effect.
1. Path specified in kwargs *should* be relative to the test file, and paths specified in CLI and ini options *should* be relative to where pytest was run.

## Non-breaking changes
- [ ] Document that backend can be specified.
- [ ] Document the option to use the full test name.
- [ ] Document that `mpl-use-full-test-name` ini overrides the `filename` kwarg.
- [ ] Add `mpl-baseline-path` ini option (relative to where pytest was run).
- [ ] Expand `mpl-use-full-test-name` ini option to CLI (and maybe kwarg)
- [ ] Add `mpl-hash-library` ini option (relative to where pytest was run).
- [ ] Add `--mpl-default-tolerance` CLI and `mpl-default-tolerance` ini options. #181
- [ ] Add CLI and ini options for `deterministic`. #197
- [ ] Add `--mpl-default-style` CLI and `mpl-default-style` ini options. #181
- [ ] Add CLI and ini options for `remove_text`.
- [ ] Add CLI and ini options for `backend`.
- [ ] Add `generate-summary` ini option for generating test summaries.

## Breaking changes
- [ ] `--mpl-hash-library` should be relative to where pytest was run (to match `--mpl-baseline-path`).
- [ ] Use Matplotlib's default style instead of `'classic'`.
- [ ] Change the default RMS tolerance to `0`.
- [ ] Enable deterministic PNG files by default.
- [ ] (???) Rename `baseline_dir`/`--mpl-baseline-path` to have consistent name.

## Future ideas
Things that might make sense but are complicated:
1. Passing `--mpl-generate-hash-library` without any value should generate to any `hash_library` kwarg file or `--mpl-hash-library` file (and an ini specified file, if added). We currently support testing with multiple hash libraries, but not generating. (Non-breaking change.)

**Comment by bjlittle** [comment]
@ConorMacBride This is brilliant! Thanks for putting this together.

I'm spinning back up on `pytest-mpl`. I've cleared the decks and pretty much secured free time to dedicate to finally getting #150 across the line.

In the process of getting my head back in the space I'm going to cross-reference your table above with the codebase and also any observations that I previously made to make sure that we've captured everything up for discussion in the `v1.0.0` roadmap.

**Comment by bjlittle** [comment]
@ConorMacBride The only additionally changes that I've noticed not captured above are:

- The `baseline_dir` kwarg takes precedence over the `--mpl-baseline-path`. The order elsewhere is CLI -> INI -> KWARG. Although, this may have changed in #181, I've not checked yet
- #150 will introduce a hashing tolerance, so we need to be able to identify the existing `tolerance` as the RMS tolerance i.e., `--mpl-rms-tolerance` (CLI), `rms-tolerance` (INI) and `rms_tolerance` (kwargs)
